### ISSUE TITLE
How to use Tvheadend with HDHRProxyIPTV

### ISSUE THREAD

**Issue by ghost** [dsaupf/HDHRProxyIPTV#29]
As the title says: how to use Tvheadend server with HDHRProxyIPTV?
I tried to change some parameters in the INI files, but it doesn't work.
Ofcourse the server does work ;-)

**Comment by dsaupf** [comment]
Hi @retrofan1979 ,

What you want to do?
- Exporting a TVH server as one HDHR tuner using the HDHRProxyIPTV tool?
- Or, use the HDHRProxyIPTV as one HDHR tuner in TVH?

**Comment by retrofan1979** [comment]
Hi, use the HDHRProxyIPTV as one HDHR tuner in TVH, but if you can show both methods, that would be nice.

**Comment by ghost** [comment]
O, I just tried an app which has both SAT>IP and HDHomeRun support, but as it didn't work with my SAT>IP server, probably due to missing QAM parameter, I tried HDHRProxyIPTV. It does work with Tvheadend as source, but not with this app. Anyway, no problem, I always could try.
