### ISSUE TITLE
Help needed with Tvheadend and minisatip to feed this proxy

### ISSUE THREAD

**Issue by ghost** [dsaupf/HDHRProxyIPTV#30]
Hi, to feed this proxy Tvheadend and minisatip can be used for example.
Can you please give some screenshots/info how to setup?
Thanks!

**Comment by retrofan1979** [comment]
Please explain both:

Exporting a TVH server as one HDHR tuner using the HDHRProxyIPTV tool.
Or, use the HDHRProxyIPTV as one HDHR tuner in TVH.

Then I try ;-)

**Comment by ghost** [comment]
.

**Comment by ghost** [comment]
.
